### PR TITLE
wrote code to unzip .gz files on windows systems

### PR DESCRIPTION
**Pull request by russodanielp**
I added a few lines of code for this to work on Windows systems.  There is probably a better way to do this like using gzip to read the xml and using elementree to parse the string, but this was more straightforward.

### CODE REVIEW

**Comment by panzarino** [comment]
@russodanielp Have you tested this? I can't test it myself on Windows, but if it works for you, I'll merge it in soon.

**Comment by russodanielp** [comment]
Yeah works on my machine....also would be available to troubleshoot any issues windows users may have.

Also, is there any documentation for the GameDay XML data provided by MLB?  I'm kinda going through your code to figure it out currently....

**Comment by panzarino** [comment]
@russodanielp I haven't found anything on the XML files, I just did my best to understand what everything is.

**Comment by panzarino** [comment]
@russodanielp yes definitely, I would really appreciate it. Please do submit a PR if you are able to make it easier. 

I'll push a release within the next couple of days with these changes.

**Comment by russodanielp** [comment]
@panzarino okay.  I believe after looking in your code there is no way to directly get batting stats for a player right?

**Comment by panzarino** [comment]
@russodanielp other than by selecting the game and then player stats and then batter stats, there is no other way to get stats for a single player right now.

**Comment by panzarino** [comment]
Released in [2.3.2](https://github.com/panzarino/mlbgame/releases/tag/v2.3.2).

**Comment by panzarino** [comment]
@russodanielp if you want to continue contributing in the future, I have set up a mlbgame Slack that you can join through this link: https://join.slack.com/mlbgame/shared_invite/MjAzMjY1MjkwOTAwLTE0OTg0MTI2MjAtMzc2NjJlMzhmYw

**Pull request merged**
