### PR TITLE
Add probable starter attributes, fixes #32

### LINKED ISSUE #32: Player ID for probable starting pitcher
In `game.scoreboard` the names and win/loss records of the probable starting pitchers are added to the game data.

```python
# games that were not played
    elif game_tag == "sg_game":
        try:
            p_pitcher_data = game.findall('p_pitcher')
            p_pitcher_home_data = p_pitcher_data[0]
            p_pitcher_home = p_pitcher_home_data.find('pitcher').attrib['name']
            p_pitcher_home_wins = int(p_pitcher_home_data.attrib['wins'])
            p_pitcher_home_losses = int(p_pitcher_home_data.attrib['losses'])
```

How could I add the player ID for the starting pitchers? I see them in the `linescore.xml`, but just adding

```python
p_pitcher_home_id = p_pitcher_home_data.find('pitcher').attrib['id']
```
doesn't work. Which data file is read here exactly?

### PR DESCRIPTION
**Pull request by ajbowler**
The overview API hits `linescore.xml` which has all of the useful probable starting pitcher info (ERA, names, player IDs, etc.)

Example: http://gd2.mlb.com/components/game/mlb/year_2018/month_02/day_25/gid_2018_02_25_chnmlb_sfnmlb_1/linescore.xml

This adds all of those attributes. Would appreciate a quick review and tag 😄 my LED board wants to scroll starting pitcher text across the screen and this file has the info readily available on at least the day before the game it seems.

### CODE REVIEW

**Comment by ajbowler** [comment]
@panzarino so it looks like the unit tests are hitting the MLB servers directly. Since the probable starter attributes are time-dependent (they go away once the game starts) any test that grabs them would start failing.

Also don't really see much I can improve upon for the code that's triggering the climate issue but I'd appreciate any feedback.

**Comment by panzarino** [comment]
@ajbowler looks good to me, for the tests that constantly change I just set it to test that the attributes are the correct type (basically just making sure they aren't null and the method actually works for the current data, ex. [test roster](https://github.com/panzarino/mlbgame/blob/master/tests/test_info.py#L222)). Can you please add tests for these new attributes and then I will merge.

**Comment by ajbowler** [comment]
@panzarino code updated. The Travis build appears to be failing on some unrelated test

**Comment by panzarino** [comment]
@ajbowler not sure why that happened, restarted the build and it passed. Great work!

**Pull request merged**
