### PR TITLE
Added Innings All File to access more detail on pitches, including PI…

### PR DESCRIPTION
**Pull request by frankmowen**
…TCHf/x data - 04/05/18 9:53 PM

Example Source URL:
http://gd2.mlb.com/components/game/mlb/year_2017/month_04/day_03/gid_2017_04_03_seamlb_houmlb_1/inning/inning_all.xml

### CODE REVIEW

**Comment by panzarino** [comment]
@frankmowen Can you please fix the pep8 issues as described by codeclimate, fix the failing tests, and fix the merge conflicts? Thanks.

**Comment by frankmowen** [comment]
@panzarino stuck on a few minor things. They might be painfully obvious but this is the first contribution I've made so I'm not sure how they are usually solved.

**Comment by Hisairnessag3** [comment]
@panzarino I would help him out with this, it obviously has a lot of useful features(and more that can be derived).

**Comment by panzarino** [comment]
@Hisairnessag3 Great! I would love to see you help out.

**Comment by frankmowen** [comment]
@Hisairnessag3 please go right ahead. If you need my help with anything just let me know.

**Comment by dgvigil** [comment]
I can take a look. I did a bit of testing and it looks like most of the failures are based on the assertion of the stat being a float `self.assertIsInstance(pitch.XXX, float)`, but on occasion they are integers.  Adding a few simple `try/except AssertionError` for types in tests/test_innings.py should fix most issues and ensure a numerical response.

The only fail is the inheritance for the [Pitch class in inning](https://github.com/panzarino/mlbgame/pull/88/files#diff-f008ad3976bd81df2ac8b6abae37f1f1R157) is not overriding the [Pitch class in events](https://github.com/panzarino/mlbgame/blob/365532125b0fe1286c32fa2471c2623e2437ab80/mlbgame/events.py#L207).

**Comment by reddigari** [comment]
Commits included and issues resolved in #120

**Pull request merged**
